/**:
  ros__parameters:
    common: 
      img_topic: ""  # 清空图像话题
      lid_topic: "/livox/lidar"  
      imu_topic: "/livox/imu"  
      img_en: 0  # 禁用图像
      lidar_en: 1  # 启用LiDAR
      ros_driver_bug_fix: false  

    extrin_calib:
      extrinsic_T: [ -0.011, -0.02329, 0.04412]
      extrinsic_R: [1.0, 0.0, 0.0,
                    0.0, 1.0, 0.0,
                    0.0, 0.0, 1.0]
      Rcl: [-0.00917, -0.99992, 0.00916, -0.01952, -0.00897, -0.99977, 0.99977, -0.00934, -0.01944]
      Pcl: [0.00642, -0.06065, -0.06363]

    time_offset:  
      imu_time_offset: 0.0  # IMU 时间偏移（单位：秒）
      img_time_offset: 0.1  
      exposure_time_init: 0.0 

    # 点云预处理
    preprocess:  
      point_filter_num: 2   # 点云下采样数量
      filter_size_surf: 0.1 # 表面点滤波尺寸
      lidar_type: 1         # mid360
      scan_line: 4  
      blind: 0.5  

    imu:  
      imu_en: true  
      imu_int_frame: 30  
      acc_cov: 0.3  
      gyr_cov: 0.2  
      b_acc_cov: 0.0001  
      b_gyr_cov: 0.0001  

    # 注释的是原来上赛季使用的参数
    lio:  
      max_iterations: 10                 # 最大迭代次数：10
      dept_err: 0.02 
      beam_err: 0.05  
      min_eigen_value: 0.005  
      voxel_size: 0.5                   # 体素尺寸：增大的很节省资源，但也会影响定位精度
      max_layer: 4  
      max_points_num: 50                # 每个体素的最大点数：增大的话可以提高定位精度，但也会增加资源消耗
      layer_init_num: [5, 5, 5, 5, 5]  

    local_map: 
      map_sliding_en: true        # 局部地图滑动：改为false性能影响太大，改为true
      half_map_size: 35           # 减小地图大小
      sliding_thresh: 8.0  

    publish:  
      dense_map_en: false         # 禁用地图发布
      pub_effect_point_en: false  # 不发布特征点
      pub_plane_en: false         # 不发布平面
      pub_scan_num: 0             # 不发布扫描点云
      blind_rgb_points: 0.0  

    pcd_save:  
      pcd_save_en: false          # 禁用地图保存  
      colmap_output_en: false  
      filter_size_pcd: 0.15  
      interval: -1 